name: ui
description: "AI AimBot Tool"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.2
  window_manager: ^0.5.1
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: zh
      fonts:
        - asset: fonts/HarmonyOS_Sans_SC_Regular.ttf
          weight: 900
  assets:
    - images/